FROM concept_gen_base:latest
WORKDIR /home/pnagula/
CMD python ./files/Code/run_summarization.py --mode=train --data_path=./files/output_files/finished_files/chunked/train_* --vocab_path=./files/output_files/finished_files/vocab --log_root=./files/pglogs/ --exp_name=firstpgexp_400 --max_enc_steps=400 --emb_dim=300 --vocab_size=90000  > ./files/logs/plog_train.log
